# Generated by Django 3.2.4 on 2021-06-30 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('literature', models.CharField(blank=True, max_length=500, null=True)),
                ('pubyear', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('ocrtext', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
