# Generated by Django 3.2.4 on 2021-10-20 12:49

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('literature', models.CharField(blank=True, max_length=500, null=True)),
                ('pubyear', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ocrtext', models.TextField(blank=True, null=True)),
                ('stm', models.TextField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('stmlist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=list), blank=True, null=True, size=None)),
                ('evlist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=list), blank=True, null=True, size=None)),
                ('ruleslist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=list), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='eng', max_length=20)),
            ],
        ),
    ]
