# Generated by Django 3.2.4 on 2021-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_remove_upload_upload_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdfs',
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
