# Generated by Django 3.2.4 on 2021-06-30 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0006_alter_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False),
        ),
    ]
