# Generated by Django 3.2.4 on 2021-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_alter_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
