# Generated by Django 3.2.4 on 2021-06-30 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0009_alter_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
