# Generated by Django 3.2.4 on 2021-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0011_alter_files_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
