# Generated by Django 3.2.4 on 2021-07-22 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0015_alter_files_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pdf',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
